### ISSUE TITLE
Can I use this to push historical data?

### ISSUE THREAD

**Issue by joernschellhaas** [gistart/prometheus-push-client#3]
I came here from https://stackoverflow.com/a/67562080/7424510.

Suppose, I've got a temperature sensor, and I've got a list of UNIX time stamps and temperatures, like so:

```
[
    (1661863713, 22),
    (1661863714, 21),
    (1661863715, 22)
]
```

Can I push this with this client? How?

**Comment by gistart** [comment]
No, you can't. It's not a specific "ingest api" client, rather it's a general purpose monitoring library.
